# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='tensorpandas',
    version='0.0.0.dev0',
    description='Tensor Extension Types for pandas and pyarrow.',
    python_requires='==3.*,>=3.6',
    project_urls={"homepage": "https://github.com/octoenergy/tensorpandas"},
    author='Igor Gotlibovych',
    author_email='igor@octopus.energy',
    license='MIT',
    packages=['tensorpandas'],
    package_dir={"": "."},
    package_data={},
    install_requires=['pandas==1.*,>=1.0.3', 'pyarrow==0.*,>=0.16.0'],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0", "flake8==3.*,>=3.7.0",
            "isort==4.*,>=4.3.0", "moto==1.*,>=1.3.14", "mypy==0.*,>=0.761.0",
            "pydocstyle==4.*,>=4.0.0", "pytest==5.*,>=5.3.0"
        ]
    },
)
