name: Tests across python and pandas versions
on:
  pull_request:
    branches:    
      - 'master'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10']
        pandas-version: ['1.1.5', '1.2.5', '1.3.5', '1.4.4', '1.5.1']

    name: "${{ matrix.os }}: python==${{ matrix.python-version }}, pandas==${{ matrix.pandas-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies  # FixMe: tie in with poetry
        run: |
          pip install pandas==${{ matrix.pandas-version }}
          pip install pyarrow
          pip install pytest
          pip install .
      - name: Run tests
        run: pytest tests/
